spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      enabled: true
      max-file-size: 2049MB
      max-request-size: 2049MB
      location: ${java.io.tmpdir}
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  h2:
    console:
      enabled: true
      path: /h2
apiPrefix: api