spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      enabled: true
      max-file-size: 2049MB
      max-request-size: 2049MB
      location: ${java.io.tmpdir}
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/shop
  messages:
    basename: messages # default value
apiPrefix: api
