spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      location: ${java.io.tmpdir}
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    driver-class-name: org.postgresql.Driver
    username: shop
    password: J98xHw4zYrf4Ykwa
  messages:
    basename: messages # default value
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxx
    password: xxx
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  thymeleaf:
    enabled: false
  rabbitmq:
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        retry:
          enabled: true
    connection-timeout: 0
    requested-heartbeat: 5
    username: broker
    password: pxnVHg47DQ95Ctkwa
apiPrefix: api
emailSender: shop@training.pl
availableLanguages: pl
defaultLanguage: pl
send-email-queue: send-email
allowed-origin: http://locallhost:4200
---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://database:5432/shop
  rabbitmq:
    host: message-broker
  jpa:
    hibernate:
      ddl-auto: update
allowed-origin: https://fullstack-developer.io